version: '2'
services:
  dbdata:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: /bin/true
  db:
    image: aidanlister/postgres-hstore
    volumes_from:
      - dbdata
    ports:
      - "5432"
  django:
    build:
      context: .
      dockerfile: Dockerfile.django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/srv/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL
      - DJANGO_SETTINGS_MODULE=onlineweb4.settings
      - OW4_PYTHON_DONT_WRITE_BYTECODE
      - OW4_DJANGO_TEST_RUNNER
      - OW4_DJANGO_DEBUG
      - OW4_DJANGO_ALLOWED_HOSTS
      - OW4_DJANGO_EMAIL_BACKEND
      - OW4_DJANGO_SECRET_KEY
      - OW4_DJANGO_BASE_URL
      - OW4_DJANGO_MEDIA_ROOT
      - OW4_DJANGO_STATIC_ROOT
      - OW4_DJANGO_SLACK_INVITER_TEAM_NAME
      - OW4_DJANGO_SLACK_INVITER_TOKEN
      - OW4_DJANGO_CORS_ORIGIN_ALLOW_ALL
      - OW4_DJANGO_STRIPE_PUBLIC_KEY_ARRKOM
      - OW4_DJANGO_STRIPE_PUBLIC_KEY_PROKOM
      - OW4_DJANGO_STRIPE_PUBLIC_KEY_TRIKOM
      - OW4_DJANGO_STRIPE_PRIVATE_KEY_ARRKOM
      - OW4_DJANGO_STRIPE_PRIVATE_KEY_PROKOM
      - OW4_DJANGO_STRIPE_PRIVATE_KEY_TRIKOM
      - OW4_DJANGO_RECAPTCHA_PUBLIC_KEY
      - OW4_DJANGO_RECAPTCHA_PRIVATE_KEY
      - OW4_DJANGO_NOCAPTCHA
      - OW4_DJANGO_RECAPTCHA_USE_SSL
      - OW4_SETTINGS
      - OW4_EVENTS_ENABLE_RECAPTCHA
      - OW4_EVENTS_FEATURED_DAYS_FUTURE
      - OW4_EVENTS_FEATURED_DAYS_PAST
      - OW4_DJANGO_GENFORS_ADMIN_PASSWORD
      - OW4_GSUITE_CREDENTIALS_PATH
      - OW4_GSUITE_SYNC_DELEGATED_ACCOUNT
      - OW4_GSUITE_SYNC_ENABLED
      - OW4_GSUITE_SYNC_ENABLE_INSERT
      - OW4_GSUITE_SYNC_ENABLE_DELETE
  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: npm start
    volumes:
      - .:/srv/app
      - /srv/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - OW4_ABAKUS_OVERRIDE
      - WEBPACK_DEV_IP=0.0.0.0
      - WEBPACK_DEV_PORT=3000
      - WEBPACK_DEV_PUBLIC_IP=localhost
